# This configures Antora for building site docs
#
# website link structure:
#
# /libs/{name}                          Redirect to /{version}/lib/{name}
# /{version}/lib/{name}                 library docs
# /{version}/lib/user-guide             User Guide
# /doc/contributor-guide
# /doc/boost-formal-review
# /develop/doc/contributor-guide
# /develop/doc/boost-formal-review
#
# /doc/libs/{old-version}/libs/{name}   redirect to versioned legacy lib docs
#
# name:         library-name
# version:      "master" | "develop" | {semantic-version}
# old-version:  DIGIT+ '_' DIGIT+ '_' DIGIT+
#

site:
  url: https://boost.revsys.dev/
  title: Boost Site Docs
  start_page: user-guide::index.adoc

antora:
  extensions:
    - require: ./extensions/boost.js
    - require: '@antora/lunr-extension'
asciidoc:
  extensions:
    - ./extensions/boost-link-inline-macro.js
    - '@asciidoctor/tabs'

content:
  sources:
    - url: https://github.com/cppalliance/site-docs
      start_path: user-guide
    - url: https://github.com/cppalliance/site-docs
      start_path: formal-reviews
    - url: https://github.com/cppalliance/site-docs
      start_path: release-process
    - url: https://github.com/cppalliance/site-docs
      start_path: contributor-guide

ui:
  bundle:
    # url: https://github.com/cppalliance/antora-ui/releases/download/ui-${page-boost-branch}/ui-bundle.zip
    url: ./antora-ui/build/ui-bundle.zip
    snapshot: true

output:
  dir: ./build
